# Generated by Django 5.1.6 on 2025-02-09 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short description of the issue', max_length=255, verbose_name='title')),
                ('description', models.TextField(help_text='Detailed explanation of the problem', verbose_name='description')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', help_text='Current resolution state of the ticket', max_length=20, verbose_name='status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Urgency level of the ticket', max_length=20, verbose_name='priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(help_text='User who created the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='tickets_tic_user_id_ee01b8_idx'), models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'), models.Index(fields=['priority'], name='tickets_tic_priorit_0bec9b_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx')],
            },
        ),
    ]
